package smartprofiler.views;

import java.util.ArrayList;
import java.util.Collection;

import smartprofiler.presenter.ProfileData;

import com.example.smartprofiler.R;

import android.content.Context;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnLongClickListener;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.CheckBox;
import android.widget.ImageView;
import android.widget.TextView;

public class ProfilesAdapter extends ArrayAdapter<ProfileData>{
	
	Context mContext;
	/**
     * The id of the resource of the layout we will use to create an
     * item in our ListView.  This value is defined in R (a gen file)
     * and generated by parsing the xml files in /res.
     */
    private int mResource;
    private ArrayList<String> mProfileDataName;
    private ArrayList<Integer> mProfileDataStatus;
    private ArrayList<ProfileData> mProfileData;
    
    /**
     * Used for Android debugging.
     */
    private final static String TAG = 
        ProfilesAdapter.class.getName();

	
	public ProfilesAdapter(Context context) {
		super(context, R.layout.profile_row );
		// TODO Auto-generated constructor stub
		mContext = context;
		mResource = R.layout.profile_row;
		
	}
	
	public void removeItem(int position){
		mProfileData.remove(position);
	}
	

	@Override
	public int getCount() {
		// TODO Auto-generated method stub
		if(mProfileData!= null)
			return mProfileData .size();
		else 
			return 0;
	}
	/**
	 * 
	 */
	@Override
    public ProfileData getItem(int position) {
       return mProfileData.get(position);
    }

    @Override
    public long getItemId(int position) {
       return position;
    }


    public ArrayList<ProfileData> getAll(){
    	return mProfileData;
    }

	@Override
	public void addAll(Collection collection) {
		// TODO Auto-generated method stub
	//	super.addAll(collection);
		mProfileData = (ArrayList<ProfileData>) collection;
	}
	
	

	@Override
	public View getView(int position, View convertView, ViewGroup parent) {
		// TODO Auto-generated method stub
		
		  ViewHolder holder;
		  String profile = mProfileData.get(position).getProfileName();
	//	  String prof = mProfileDataName.get(position);
		  Log.d(TAG, profile);
		
		 if (convertView != null) {
	            // Get the parts of this view that's already been
	            // instantiated.
	            holder = (ViewHolder) convertView.getTag();
	        } else {
	            // We don't have a view to convert, make one.
	            convertView =
	                LayoutInflater.from(getContext()).inflate(mResource,
	                                                          parent,
	                                                          false);
	            holder = new ViewHolder();
	            holder.profile = (TextView)
	                convertView.findViewById(com.example.smartprofiler.R.id.profileView1);
	            holder.profile.setText(profile);
	            convertView.setTag(holder);
	            holder.image = (ImageView) convertView.findViewById(com.example.smartprofiler.R.id.imageView1);
	            if(mProfileData.get(position).getProfileStatus()==1)
	            	holder.image.setImageResource(R.drawable.ic_done_white_24dp);
	           
	            
	        }
		
		return convertView;
			
	}
	
	
	  /**
     * Private class that holds the ImageView.
     */
    private class ViewHolder {
        TextView profile;
        ImageView image;
    }

}
